### ISSUE TITLE
Document remote debugging

### ISSUE THREAD

**Issue by eric-schleicher** [google-ar/WebARonARCore#11]
Still a bit hard to see exactly what/where errors occur.   Is there a way to get insight into error either on the device or with a remote debugger?

-Eric

**Comment by jsantell** [comment]
You can debug it with Chrome remote debugger like you would other webviews: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews#open_a_webview_in_devtools

**Comment by jsantell** [comment]
That being said, we should document this in the README. Updating title

**Comment by eric-schleicher** [comment]
thanks.   i did find this in my own search but hadn't done it yet.   will do now!

**Comment by eric-schleicher** [comment]
Hello @jsantell getting around to get this setup, have some additional questions.  I've read the instructions on enabling remote debugging, but still wasn't able to get it sorted.

I went through the steps (on windows)  prep the phone for remote debugging.  Despite the device manager seeing the phone (s8 usb drivers installed; and debugging remote webviews enables in developer settings) when I run the pre-built apk (demo scene), I don't see any new entries on locally connected pc @ `chrome://inspect`, even after refreshing.

So first question is whether that is the expected result?  does the pre-built apk have remote debugging of webviews enabled?  

Reviewing the repo, i see that 
`WebView.setWebContentsDebuggingEnabled(true)` is used [here](https://github.com/google-ar/WebARonARCore/blob/5cf791c61c218304b8e9e8c24a0abf1cf250a93d/chrome/test/chromedriver/test/webview_shell/java/src/org/chromium/chromedriver_webview_shell/Main.java#L27) 

Am I right that this is just part of test(s) but doesn't end up in the apk?  

If the pre-built apk doesn't have this enable, I don't mind building from source, i just didn't want to venture off a cliff if i didn't need to and it was something else silly.  

**Do i need to build from source with the `WebView.setWebContentsDebuggingEnabled(true)` addition?**
pointers appreciated.

**Comment by jsantell** [comment]
For a quick response, you shouldn't have to rebuild Chromium, the APK should support it out of the box.

Just to confirm, when opening Chrome on your Android phone, do you see Chrome for Android's tabs in `chrome://inspect`?
