### ISSUE TITLE
S8+ Support?

### ISSUE THREAD

**Issue by J4S0Nc** [google-ar/WebARonARCore#13]
Any eta for S8+ support?

**Comment by YoneChen** [comment]
cannot run in S8 SM-G9500, need help.
Alert "ERROR This device is not currently supportedby WebARonARCore"

**Comment by nathanmartz** [comment]
I'm sorry, but S8+ is not supported during the ARCore developer preview.

**Comment by nathanmartz** [comment]
PS - the PM9500 variation of the S8 is a separate issue. Our device team is looking into that one.

**Comment by YoneChen** [comment]
Thanks, I can't wait to get startted

**Comment by patricknelson** [comment]
On a related note, is this build compatible with the new  Pixel 2 that just recently came out? Got some budget for hardware for development and weighing my options and so far it looks like Galaxy S8 is my only option here.

**Comment by jsantell** [comment]
The Pixel 2 and Pixel 2 XL are both ARCore compatible devices, so this build of Chromium should work on those devices

**Comment by elCanarioVidal** [comment]
Hi guys,
with the sdc2017 announcement what ARCore soon extend to the Galaxy S8+ and Galaxy Note 8, are you consider release an update for those devices?
