### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by mayrenia-lee** [google-ar/WebARonARCore#14]
The ability to deep link into WebARonARCore app would be very useful.

Given a custom uri scheme, e.g, googlewebar:// and allowing the passing of URL as a parameter could reduce friction, improve onboarding experience and enable these scenarios

## Scan QR Code to WebAR experience
* User scans a QR Code that has a uri as the content, e,g googlewebar://url/https://example.com/amazingar.html
* WebARonARCore app opens and loads the supplied URL

## Web page link to WebAR experience
* User clicks a link on a web page that has the custom scheme, e.g, googlewebar://url/https://example.com/mindblowingar.html
* WebARonARCore app opens and loads the supplied URL

**Comment by judax** [comment]
This feature will land once #43 is approved and merged.

**Comment by judax** [comment]
This feature just landed. webar:// http:// and https:// can be used as schemes.
