### ISSUE TITLE
S8 SM-G9500 not supported

### ISSUE THREAD

**Issue by YoneChen** [google-ar/WebARonARCore#15]
Cannot run in S8 SM-G9500.
Alert "ERROR This device is not currently supportedby WebARonARCore"

**Comment by nathanmartz** [comment]
This is a known issue as during the preview we only support the specific models listed here: https://devsite.googleplex.com/ar/discover/#supported_devices. We have received requests for this device from other devs and are looking into supporting it, but not ETA right now.

**Comment by Archie1978** [comment]
Hello, 
https://devsite.googleplex.com/ar/discover/#supported_devices, I don't authorized to see. 

    I have ARM Cortex A-53 with Mali-T720 for HT30 Pro ( hardware mt6737 ) and I have a same problem

**Comment by jsantell** [comment]
@Archie1978 try this link: https://developers.google.com/ar/discover/#supported_devices
