### ISSUE TITLE
self signed HTTPS bypass

### ISSUE THREAD

**Issue by liabru** [google-ar/WebARonARCore#19]
I'm hosting a local development server, proxied to my device using `chrome://inspect`. The features I need to use are HTTPS only so I must host with a self-signed cert for development.

Normally, in Chrome you'd get a message "Your connection is not private" which you must bypass and this works fine on the desktop browser. But the WebARonARCore browser doesn't have a bypass screen, it just shows an `net::ERR_CONNECTION_REFUSED` error.

Is there a way this can be enabled? It's important for features like geolocation. Thanks.

**Comment by msimpson** [comment]
@liabru 
Did you ever try importing your self-signed certificate on your device? For example:
[Add self signed SSL certificate to Android (for browsing)](https://coderwall.com/p/wv6fpq/add-self-signed-ssl-certificate-to-android-for-browsing).

**Comment by jsantell** [comment]
In the mean time, I believe you can use `localhost` on http and the SSL-required features are allowed

**Comment by liabru** [comment]
@msimpson ah that looks useful!

@jsantell actually in the end that's what I used, it turns out because I was using `127.0.0.1` I was having the issue, it does not seem to allow it like `localhost` does.

I think both of these approaches seem acceptable, so this can probably be closed?

**Comment by jsantell** [comment]
I ran into the same issue when using `0.0.0.0` and discovering that `localhost` is a special string allowing the SSL-required features :)

I'll leave this open for now incase @judax @lincolnfrog have any thoughts on the difficulty of enabling the https bypass page. If it's quick & easy, could be a nice fix, otherwise this workaround can suffice

**Comment by judax** [comment]
A new version is coming soon and it should resolve this issue. Stay tuned!
