### ISSUE TITLE
Capture the crash on devices not supported by ARCore

### ISSUE THREAD

**Issue by judax** [google-ar/WebARonARCore#2]
and display a message stating that the prototype browser is not yet supported in the device (and maybe a list of the supported devices).

**Comment by sohanjg** [comment]
Hi, 

I am a Chromium developer, and was interested with you work here.
Any idea when will the webview be available for Huawei devices ? Currently it crashes with missing Tango libs.
I guess the problem is with ARCore support, which in preview do not exist beyond pixel and s8 device ? Or is there some other hardware dependencies too ?

Thanks.

**Comment by judax** [comment]
Correct. You need a Pixel, Pixel XL or a Samsung Galaxy S8 all with at
least Android N (7.0+) to be able to use ARCore while it is in developer
preview. This situation
May change in the future when ARCore is officially released to the wider
audience but cannot say what devices will be supported.

**Comment by sohanjg** [comment]
Thanks.
May be un-related to the Issue here, but wanted to understand the use of ppapi in this chromium implementation.
Are you using 3rd party extension support via ppapi ? AFAIK for mobile chrome ppapi is not supported.
Is this a short term plan ?

**Comment by sohanjg** [comment]
Hi,

Sorry for all the noise here, not exactly an issue.

Just wanted to understand how do you access arcore sdk code from Chromium, from what i see for simple apps, the flow is
App->VR/WebGL->Tango Service (api's)

Or is all access to arcore api's happens from inside Tango libs/service ?

How can arcore Java api's https://developers.google.com/ar/reference/java/com/google/ar/core/package-summary be accessed from Chromium ?

Or we work with this set of api's for now ?
https://github.com/google-ar/three.ar.js/blob/master/API.md

Thanks!

**Comment by MikelSalazar** [comment]
Hello (again) Judax,

   I have been trying to test this prototype but it seems that the Nexus 9 I have is not --yet--supported. Can you confirm whether or not the new Google Pixel 2 will be in the list of supported devices at release?

Thanks and keep the good work.

**Comment by jsantell** [comment]
The pixel 2 will be an ARCore compatible device; we haven't tested yet, but WebARonARCore should work on the pixel 2 and pixel 2 XL

**Comment by judax** [comment]
PR #7 resolves this issue. Closing.
