### ISSUE TITLE
Application is crashing during startup

### ISSUE THREAD

**Issue by sarathsi** [google-ar/WebARonARCore#22]
Environment: Ubuntu 14.04. 
WebARCore app is crashing during startup.
10-13 11:18:46.201  9409  9409 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)

--------- beginning of crash
10-13 11:18:46.201  9409  9409 E AndroidRuntime: FATAL EXCEPTION: main
10-13 11:18:46.201  9409  9409 E AndroidRuntime: Process: org.chromium.android_webview.shell, PID: 9409
10-13 11:18:46.201  9409  9409 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at org.chromium.android_webview.shell.AwShellActivity.tryToConnectWithTango(AwShellActivity.java:503)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at org.chromium.android_webview.shell.AwShellActivity.onResume(AwShellActivity.java:531)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7079)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-13 11:18:46.201  9409  9409 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

10-13 11:18:46.203  1091  2382 W ActivityManager:   Force finishing activity org.chromium.android_webview.shell/.AwShellActivity

**Comment by nathanmartz** [comment]
Did you install the arcore-preview.apk? It looks like probably not.

**Comment by sarathsi** [comment]
Oh... just installed arcore-preview.apk and problem is solved. Thank you. Sorry for trouble.
