### ISSUE TITLE
Install apk version erreur

### ISSUE THREAD

**Issue by Archie1978** [google-ar/WebARonARCore#24]
Hello,
   when I install WebARonARCore on android 6.0. The message is (in french sorry)
"Erreur d'analyse. Un probleme est survenu lors de l'analyse du package".
I had actived the "software unknown" in my configuration :x.

I think it's just my android too old.

Can it work for android 6.0 ?

**Comment by nathanmartz** [comment]
Yes. ARCore requires 7.0 (N) or above.
