### ISSUE TITLE
InstaCrash on Pixel XL 1 on Android 8.0.0

### ISSUE THREAD

**Issue by dmarcos** [google-ar/WebARonARCore#30]
I installed the latest version of the [WebAROnARCore.apk](https://github.com/google-ar/WebARonARCore/commit/f8142f264aa34f84cabfd62eb2c0da4f8ccbb17f#diff-7cd79b7069065c8f0b6176107fd64624) and I get an instacrash when launching it with a message `WebARCore keeps stopping`. 

![screenshot_20171031-133042](https://user-images.githubusercontent.com/39342/32247635-30051942-be40-11e7-8884-556e9c28e1a1.png)

**Comment by jsantell** [comment]
Hey Diego, do you also have [ARCore installed](https://github.com/google-ar/WebARonARCore#1-install-the-arcore-apk)?

**Comment by dmarcos** [comment]
Thanks. Yeah it works now. I had not read the instructions and wrongly assumed that all the ARCore stuff would come working out of the box with Oreo. Closing.
