### ISSUE TITLE
Refresh/back buttons do not consistently work

### ISSUE THREAD

**Issue by jsantell** [google-ar/WebARonARCore#32]
Partially due to not having 'click' feedback, it's unclear whether these work. Sometimes WebARonARCore can get in a funky state where buttons don't work, and lacking feedback and the delay (in reloading) leads to confusion.

**Comment by judax** [comment]
Tried some approaches like changing the color of the button when is pressed but as the buttons are not very big, there is not much that can be done to highlight that they have been pressed. Do you have any other suggestions? How about making the back button to be disabled when there is no pages to go back to anymore?

**Comment by judax** [comment]
Closing this one for now. Please, reopen if there is any suggestion on how to improve it.
