### ISSUE TITLE
Crashes when launched on Pixel 1 XL

### ISSUE THREAD

**Issue by arpo** [google-ar/WebARonARCore#35]
After the permissions has been granted the app crashes on my device. Has anyone else experienced this?

**Comment by judax** [comment]
Could you send us the logcat? Do you have the [ARCore APK](https://github.com/google-ar/arcore-android-sdk/releases/download/sdk-preview/arcore-preview.apk) installed along with the WebARonARCore APK?

**Comment by arpo** [comment]
My bad! Missade the APK installation. Would it be possible to add a feature-detection-if-statement that alerts the user to install the APK if it's missing?

**Comment by jsantell** [comment]
@arpo we have #31 open for just that case to have a more helpful message in this scenario. Thanks for filing this issue, hope to add that message soon!
