### ISSUE TITLE
Does WebARonARCore support the similiar getPixelIntensity func of ARCore for lightEstimate?

### ISSUE THREAD

**Issue by godlzr** [google-ar/WebARonARCore#39]

**Comment by jsantell** [comment]
Light estimation is not yet exposed for WebARonARCore/WebARonARKit. We're exploring this currently and is on our roadmap!

**Comment by godlzr** [comment]
@jsantell, thanks for the reply, any idea about when lightEstimate will be ready?

**Comment by jsantell** [comment]
We don't have any info to share on timeline for light estimation quite yet
