### ISSUE TITLE
WebGL error spam and ARView failing to render

### ISSUE THREAD

**Issue by jsantell** [google-ar/WebARonARCore#41]
Using the [latest APK](https://github.com/google-ar/WebARonARCore/blob/5f3ebff8af1da636c6ea71f0de1b1ef1cda48f3a/apk/WebARonARCore.apk), on first load, I get an all black ARView (with THREE elements rendering on top of the black ARView) and a handful of log spam:

![consolespam](https://user-images.githubusercontent.com/641267/33141397-dde18c0c-cf67-11e7-9fa2-024fdaf2f797.png)

The warnings happen in both `gl.bindTexture` commands within ARView. On reloading the page, the screen renders, but still get the log spam. This did not happen in a previous build

**Comment by judax** [comment]
Something is off because I have not been able to reproduce this error. Would you mind installing the latest APK and trying the basic examples just to make sure?

**Comment by judax** [comment]
@jsantell are you still experiencing this issue?

**Comment by jsantell** [comment]
I am no longer able to reproduce! Closing..
