### ISSUE TITLE
Are these projects will be merged into Chromium?

### ISSUE THREAD

**Issue by LantosIstvan** [google-ar/WebARonARCore#42]
Is there any future plans to merge this project (`WebARonARCore`) into the main Chrome for Android browser?  And merge `WebARonARKit` into Chrome for iOS?

**Comment by msimpson** [comment]
I think this was touched on in google-ar/three.ar.js#82.

**Comment by jsantell** [comment]
We are starting the standards process with the goals of landing a standardized API in Chrome in the future -- I'll post a link in google-ar/three.ar.js#82 when the initial standards work repo is live. Thanks!
