### ISSUE TITLE
Samsung Galaxy Note 8 Support 

### ISSUE THREAD

**Issue by seflless** [google-ar/WebARonARCore#45]
I was under the impression you could now use Arcore on recent Samsung devices. I get a "device not supported" popup when running the AR browser. 

Maybe there just needs to be a new build with a more recent Arcore library?

**Comment by jsantell** [comment]
The note 8 is not yet [a supported device](https://developers.google.com/ar/discover/) -- there's been [an announcement](https://9to5google.com/2017/10/18/samsung-google-partnership-arcore-galaxy-note8/) that the S8+ and Note 8 will support ARCore, but that is not the case quite yet

**Comment by Francois-Laberge-Bose** [comment]
Looks like they are saying they support S8 now, but Note 8s are not listed:
![s8-supported](https://user-images.githubusercontent.com/34040155/33908375-35796b80-df56-11e7-8f4d-53f6c7cb6a1c.PNG) (From your link https://developers.google.com/ar/discover/)

**Comment by Francois-Laberge-Bose** [comment]
I have an S8 also, so I'll try that out and report back.

**Comment by jsantell** [comment]
S8 is supported, the S8+ however not quite yet :) closing this issue for now, thanks!
