### ISSUE TITLE
Detect blur event or when user returns to home screen?

### ISSUE THREAD

**Issue by andrelevi** [google-ar/WebARonARCore#46]
Right now my app uses a websocket connection. I'd like to break it when the user minimizes the app and returns to the home screen. The blur event is not fired when this happens, but it is fired on Mozilla's webxr viewer. Is there a way I can detect when the user has minimzed the app? Thanks!

**Comment by jsantell** [comment]
Thanks for filing! We'll get back to you with some more info after the holidays

**Comment by judax** [comment]
We are working on a major reimplementation of this prototype browser. This new implementation will resolve many issues listed including this one. Please, stay tuned. Cannot provide an estimate on when it will be ready though, sorry.
