### ISSUE TITLE
About supported device.

### ISSUE THREAD

**Issue by hyunsooda** [google-ar/WebARonARCore#49]
Hi! I'm korean university student.
I have a question.
Your WebARonARCore said that support only S8 device but, I'm using note 5 so, I got a popup as "my device is not supported" after downloding APK with my phone so, I wonder that this library support only new device? if so, I think that it cannot attract people those using older phone rather than S8 and I  can't research this library.
by any chance this library will support only new device now and forever?
Have a nice day.

**Comment by robertjuh** [comment]
i heard stories about ARCore coming to more devices in the future, i also discovered a new project: 'usensAR' which is not launched yet.

There have been people with a hack to make it work on older devices, however the callibration is horribly off in these cases.

**Comment by jsantell** [comment]
WebARonARCore can only run on devices that support ARCore; [supported ARCore devices can be found here](https://developers.google.com/ar/discover/#supported_devices). It's up to the ARCore team to decide what devices are capable and when to be supported. I hope this helps!
