### ISSUE TITLE
ARCore on OnePlus 3T

### ISSUE THREAD

**Issue by karanganesan** [google-ar/WebARonARCore#5]
Since Pixel and Pixel has same processor as OnePlus 3T and yes the camera's are different ! Anyways can anyone help have a OnePlus 3T build of APK ??? 

Cc @OnePlusOSS & @XDA

**Comment by nathanmartz** [comment]
Qualifying a device for AR involves many aspects of the phone, not just the SoC and camera. We'll add more device support over time, but during the preview only the pixel and s8 are supported.

**Comment by karanganesan** [comment]
Okk

**Comment by jsantell** [comment]
You can try this project, I haven't tried it and think it involves some hacking, but if you're feeling adventurous and risky, https://github.com/tomthecarrot/arcore-for-all

**Comment by flurbius** [comment]
Thanks that looks like the only option for some of us
