### ISSUE TITLE
SM-G955FD

### ISSUE THREAD

**Issue by renalombardero** [google-ar/WebARonARCore#54]
I have an S8+ but when I try to run the browser it says that the device is not supported. 

Is this the case? 

I'm running Android 7.0.

Thought that since S8 and S8+ are basically the same device it would work. 

Thanks

**Comment by judax** [comment]
Hello, yes, the currently supported devices are Pixel 1, Pixel 2, Pixel 1 XL, Pixel 2 XL and Samsung Galaxy S8.

Sorry.
