### ISSUE TITLE
Galaxy S7 support

### ISSUE THREAD

**Issue by urish** [google-ar/WebARonARCore#55]
Seems like Galaxy S7 is now officially supported by ARCore: https://developers.google.com/ar/discover/#supported_devices

Is it also supported by WebARonARCore? If so, do would you like me to send a PR to update the [list of supported devices](https://github.com/google-ar/WebARonARCore#1-install-the-arcore-apk) in README?

**Comment by judax** [comment]
Thank you for the note. What is happening is that WebARonARCore is based on ARCore DP1 (were only Pixel devices and S8 were supported). DP2 now supports more devices. The biggest problem is that adding DP2 support internally requires significant changes. We are studying some possible solutions. We will update this issue as we find the right solution.

**Comment by urish** [comment]
Thank you so much!

I really admire your work on this project, and I am very excited about the endless possibilities it will create for authoring cross-platform AR content for the web. I even created a detailed step-by-step tutorial guiding fellow developers how to use this magical technology:

https://medium.com/@urish/web-powered-augmented-reality-a-hands-on-tutorial-9e6a882e323e

As soon as DP2 support lands, I will update my tutorial to reflect the new supported devices.

Thanks again, and keep up the good work!

**Comment by judax** [comment]
#57 has landed already. Please, be mindful that the current version of WebARonARCore is not built against the ARCore 1.0 SDK. Still, as the communication bridge between the API and the ARCore service is the same, it seems to be working well. We are working on a major reimplementation of this whole project on top of the latest Chromium and ARCore. ETA still TBD.
