### ISSUE TITLE
Running into cache issues and having to uninstall/reinstall

### ISSUE THREAD

**Issue by sniejadlik** [google-ar/WebARonARCore#56]
the experimental application we have built works great on the first pass through.  but any subsequent pass encounters an error where the AR layer were are embedding is hidden.  We are assuming it's a caching issue with the loading of everything that is going on.  For our demonstration purposes it's minor but it does mean that we have to completely uninstall and then reinstall the browser on every test.  Is there any way to add in a clear cache feature to the browser?

**Comment by judax** [comment]
Would you mind elaborating a bit more on what so you mean by "subsequent pass"? Do you mean that the whole screen turns black?

**Comment by anutin544** [comment]
Ok

**Comment by judax** [comment]
Any update on this issue?

**Comment by judax** [comment]
Closing. Feel free to reopen if you can provide more information.

**Comment by sniejadlik** [comment]
Sorry I never saw your reply message asking for more details.

What I meant by subsequent pass was if we ever had to close the browser and start again.  The AR application would only ever work on the first successful build of the browser and app.  When we were done with a demo and wanted to show it again we had to completely delete the browser and reinstall it.  It appeared to be a cache issue but the experimental build has no ability to clear cache or memory.
