### ISSUE TITLE
Moving objects by dragging rather than 'teleporting' them

### ISSUE THREAD

**Issue by robertjuh** [google-ar/WebARonARCore#58]
Hello,

Would it be possible to move objects over a plane with a drag motion? This instead of the process of tapping on a place in the plane and the object will teleport or clone there?

If it's not made yet, i could give it a try to make it myself but i'm not sure where to start maybe you have suggestions?

**Comment by msimpson** [comment]
You could listen to **planesadded**, **planesupdated**, and **planesremoved** to create, update, and remove surface extents to which you could clamp the Y axis of your game objects. Those events are emitted by the **ARDisplay**, which is returned by the promise generated from the **getARDisplay** method of **THREE.ARUtils**.

I did something similar when I layered ammo.js over the scene with surfaces tessellated as a ground objects with which other game objects would collide. Some of my initial questioning and code can be found in [this issue](https://github.com/google-ar/three.ar.js/issues/75) on the THREE AR repository.

**Comment by judax** [comment]
I think this question fits better in the [three.ar.js](https://github.com/google-ar/three.ar.js/issues) repo. I would suggest/encourage you to re-post it there. Happy to reply once you do with some suggestions.
