### ISSUE TITLE
support for new device

### ISSUE THREAD

**Issue by checksummaster** [google-ar/WebARonARCore#60]
since arcore 1.0 more device should be supported ... in my case samsung s8+

**Comment by urish** [comment]
See #57 - I hope they will merge it soon

**Comment by judax** [comment]
#57 has landed already. Please, be mindful that the current version of WebARonARCore is not built against the ARCore 1.0 SDK. Still, as the communication bridge between the API and the ARCore service is the same, it seems to be working well. We are working on a major reimplementation of this whole project on top of the latest Chromium and ARCore. ETA still TBD.
