### ISSUE TITLE
Samsung Galaxy S7 

### ISSUE THREAD

**Issue by StudioZAAK** [google-ar/WebARonARCore#66]
Installed ARCore APK + WebARonARCore APK directly on my Samsung Galaxy S7 Device via the links provided by https://github.com/google-ar/WebARonARCore. Running WebARonARCore i get an alert "ARCore is not installed" alltough it definitely is. Any suggestion on this? 

Samsung Galaxy S7 | SM-G930F 
Android 7.0 | Build Nr. NRD90M.G930FXXU2DRB6

**Comment by judax** [comment]
This is related to #61 . Please, install https://github.com/google-ar/arcore-android-sdk/releases/download/sdk-preview/arcore-preview.apk

I will push a new PR to fix the documentation. Closing this issue. Open it back if needed.
