### ISSUE TITLE
ARCORE failing to install 

### ISSUE THREAD

**Issue by das-maatra** [google-ar/WebARonARCore#67]
Hello,

I am trying to run the sample projects from the Github page. But whenever I open up the WebARonARCore browser I get an error saying "ARCore not installed". I have already installed arcore-preview2.apk via adb. The browser was installed via adb as well. I am using a Google Pixel 2 XL. I would appreciate it if someone could point out suggestions. Thanks and regards.

**Comment by vincentfretin** [comment]
Hi,
WebARonARCore only works with arcore-preview.apk
actually https://github.com/google-ar/WebARonARCore/pull/53 shouldn't have been merged.

**Comment by sandblasted7** [comment]
Hello,

Thank you for the reply. So what is the standard package that should be used to build three.ar.js projects on a google pixel 2 XL?
Is there a new browser for the arcore.preview2.apk ? 

Thanks.

**Comment by judax** [comment]
#68 has landed. Closing this issue. Reopen if you need to.

**Comment by jaiwardhan** [comment]
Installation fails with [this](https://github.com/google-ar/WebARonARCore/raw/webarcore_57.0.2987.5/apk/WebARonARCore.apk) apk. Tried on android emulator Pixel/Pixel2/XL variants.
@judax Can you please update this thread and reopen this?
![image](https://user-images.githubusercontent.com/5751535/42710753-f9abfd16-8702-11e8-9a1e-9edd44fc0e13.png)

**Comment by jaiwardhan** [comment]
The same issue happens when I try to install from the direct apk over the emulator browser.
So basically the step-2 of [this](https://github.com/google-ar/WebARonARCore) setup has failed and at least I am unable to proceed.
![image](https://user-images.githubusercontent.com/5751535/42710815-3e8693d8-8703-11e8-996a-8444b753a609.png)

**Comment by riccardogiorato** [comment]
Got the same problem described in the previous comments. Can't manage to install WebARonARCore on Android Emulator.

**Comment by judax** [comment]
I have never tried WebARonARCore on the emulator. Just tried and the Dev Preview 1 APK installed with no problem but the WebARonARCore APK starts to install but seems to never finish. Sorry, cannot provide much more insight than this. Still, this project should be considered nearly deprecated. We are working on a new version based on the WebXR device API hopefully to be released soon.
