### ISSUE TITLE
Update to ARCore 1.2?

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/WebARonARCore#73]
I know Google is working on bringing AR functionality to regular Chrome browser. But this seems to be still far away. Any chance to get WebARonARCore updated so ARCore 1.2 features can be used?

**Comment by robertjuh** [comment]
They're working on bringing it to a newer version of Chromium and a newer version of ARCore (1.1 or 1.2) but they can't give a time estimation yet

**Comment by michaelvogt** [comment]
Fair enough. Knowing that there is work done in this direction is good to know.
Thanks for the answer.
